{% set name = "jinja2-git" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jinja2-git-{{ version }}.tar.gz
  sha256: 20b15497548cf86eefb116b11141e30ed2a690e0ea5d71f0e5cd17ccdf77491a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.2.0
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - jinja2 >=2.10,<4.0

test:
  imports:
    - jinja2_git
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wemake-services/jinja2-git
  summary: Jinja2 extension to handle git-specific things
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
